name = "murder-mystery-creator"
main = "./dist/server/index.js"
compatibility_date = "2026-01-06"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./dist/client"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "murder-mystery-create-db"
database_id = "0ce6ce02-e7e3-412e-83c0-e4ef84b483db"

[build]
command = "pnpm build"
