name = "murder-mystery-creator"
main = "./dist/server/entry.mjs"
compatibility_date = "2026-01-06"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "murder-mystery-db"
database_id = "your-database-id"
